hygie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hygie_portal.urls')),
    path('admin/', admin.site.urls),
]

hygie_portal/urls.py
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from hygie_portal.forms import LoginForm
from . import views

app_name = "hygie_portal"

urlpatterns = [
    #path(r'login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name='login'),
    #path("", LoginView.as_view(template_name='public/login.html'), name='login'),
    path('login/', views.login_request, name='login'),
    path('', RedirectView.as_view(url='/login/')),
    
    path('profile/', views.profile, name='profile'),
    
    #path('home/', TemplateView.as_view(template_name='users/home_public.html'), name='home_public'),
    
    path('ticket_search/', views.ticket_search, name='ticket_search'),
    
    path('home/', views.home, name='home'),
    path('logout/', views.logout_request, name='logout'),
    
    path('change_view/<str:view_type>/', views.change_view , name='change_view'),
    
    path('members/', views.members, name='members'),
    path('holidays/', views.holidays, name='holidays'),
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('get_team_trends/', views.get_team_trends, name='get_team_trends'),
    path('classic_dashboard_load_group/', views.classic_dashboard_load_group, name='classic_dashboard_load_group'),
    path('classic_dashboard_state_save/', views.classic_dashboard_state_save, name='classic_dashboard_state_save'),
    
    path('custom_dashboard/', views.custom_dashboard, name='custom_dashboard'),
    path('save_settings/', views.save_settings, name='save_settings'),
    
    path('tickets/open/team/<str:team>/', views.team , name='team'),
    path('tickets_notes_json/', views.tickets_notes_json, name='tickets_notes_json'),
    
    
    path('security/<str:security_type>/', views.security , name='security'),
    path('security_details/<str:security_type>/', views.security_details , name='security_details'),
    #path('security_search/<str:security_type>/', views.security_search , name='security_search'),
    
    
    path('patch_followup', views.patch_followup, name='patch_followup'),
    path('patch_management', views.patch_management, name='patch_management'),
    path('patch_save', views.patch_save, name='patch_save'),
    path('patch_delete', views.patch_delete, name='patch_delete'),
    #path('patch_search/<str:security_type>/', views.patch_search , name='patch_search'),
    #path('patch_edit/<str:security_type>/', views.patch_edit , name='patch_edit'),
    #path('patch_customsearch/<str:security_type>/', views.patch_customsearch , name='patch_customsearch'),
    path('patch_detail_search/<str:security_type>/', views.patch_detail_search , name='patch_detail_search'),
    path('patch_device_info/<str:security_type>/', views.patch_device_info , name='patch_device_info'),
    path('tickets_notes_json', views.tickets_notes_json, name='tickets_notes_json'),
    
    path('discrepancy/<str:discrepancy_type>/', views.discrepancy , name='discrepancy'),
    path('except_discrepancy/<str:discrepancy_type>/', views.except_discrepancy , name='except_discrepancy'),
    path('discrepancy/ticketstatus', views.ticket_status, name='ticket_status'),
    
    path('ostype/<str:server_type>/', views.ostype , name='ostype'),
    
    path('cmdb/', views.cmdb, name='cmdb'),
    path('cmdb_json/', views.cmdb_json, name='cmdb_json'),    
    path('oneretail_json/', views.oneretail_json, name='oneretail_json'),  
    path('exclusion_json/', views.exclusion_json, name='exclusion_json'),
    path('oneretail_exclusion_json/', views.oneretail_exclusion_json, name='oneretail_exclusion_json'),
    path('oneretail_delete_json/', views.oneretail_delete_json, name='oneretail_delete_json'),
    path('delete_json/', views.delete_json, name='delete_json'),
    path('device_information/', views.device_information, name='device_information'),
    path('oneretail_device_information/', views.oneretail_device_information, name='oneretail_device_information'),
    
    path('quality/', views.quality, name='quality'),
    path('save_rca/', views.save_rca, name='save_rca'),
    path('edit_rcareport_quality/', views.edit_rcareport_quality, name='edit_rcareport_quality'),
    path('delete_rca/', views.delete_rca, name='delete_rca'),
    
    path('reporting_esurvey/', views.reporting_esurvey, name='reporting_esurvey'),
    path('get_esurvey_details/', views.get_esurvey_details, name='get_esurvey_details'),
    
    path('closed_tickets/', views.closed_tickets, name='closed_tickets'),
    path('reporting/topten/', views.reporting_topten, name='reporting_topten'),
    path('save_topten/', views.save_topten, name='save_topten'),
    
    path('reporting/tsc_calendar/', views.reporting_tsccalendar, name='reporting_tsccalendar'),
    path('reporting/nest_calendar/', views.reporting_nestcalendar, name='reporting_nestcalendar'),
    
    path('reporting/ticket_stats/', views.reporting_ticket_stats, name='reporting_ticket_stats'),
    path('reporting/<str:ticket_analysis_type>/', views.reporting_ticket_analysis , name='reporting_ticket_analysis'),
    
    path('reporting/integration_view/<str:view_mode>/', views.reporting_integration_view , name='reporting_integration_view'),

    path('hypervision_oneretail/', views.hypervision_oneretail, name='hypervision_oneretail'),
    
    path('control_plan_global/', views.control_plan_global, name='control_plan_global'),
    path('control_plan_ko/', views.control_plan_ko, name='control_plan_ko'),
    path('control_plan_domain/', views.control_plan_domain, name='control_plan_domain'),
    path('control_plan_businessflag/', views.control_plan_businessflag, name='control_plan_businessflag'),
    
    path('admintools/control_plan_management/', views.control_plan_management, name='control_plan_management'),
    
    path('admintools/query_management/', views.query_management, name='query_management'),
    path('admintools/query_edit/', views.query_edit, name='query_edit'),
    path('admintools/query_save/', views.query_save, name='query_save'),
    path('admintools/query_delete/', views.query_delete, name='query_delete'),
    
    
    path('admintools/content_management/', views.content_management, name='content_management'),
    path('admintools/content_save/', views.content_save, name='content_save'),
    path('admintools/content_edit/', views.content_edit, name='content_edit'),
    path('admintools/content_delete/', views.content_delete, name='content_delete'),
]

hygie_portal/models.py
from django.db import models

# Create your models here.
from django.db import models
from django import forms
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
import bcrypt
from datetime import datetime
#import ldap

class Applications(models.Model):
    name = models.CharField(unique=True, max_length=200)

    class Meta:
        managed = True
        db_table = 'applications'
        
class Contentmanager(models.Model):
    title = models.CharField(max_length=80, blank=True, null=True)
    description = models.CharField(max_length=80, blank=True, null=True)
    module = models.CharField(max_length=80, blank=True, null=True)
    contenttext = models.TextField(blank=True, null=True)
    lastupdated = models.DateTimeField(blank=True, null=True)
    lastuser = models.CharField(max_length=80, blank=True, null=True)
    allowedaccess = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'contentmanager'        
        
class CustomUser(AbstractUser):
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    #is_active = models.IntegerField(blank=True, null=True)
    is_admin = models.IntegerField(blank=True, null=True)
    role = models.CharField(max_length=256, blank=True, null=True)
    
    #USERNAME_FIELD = 'user'
    #REQUIRED_FIELDS = []
    
    '''def is_active(self):
        return True'''
        
    def set_is_admin(self, is_admin):
        self.is_admin = is_admin

    def set_role(self, role):
        self.last_update = datetime.now()
        self.role = role
        
class Holidays(models.Model):
    uid = models.CharField(unique=True, max_length=80)
    summary = models.CharField(max_length=80)
    region = models.CharField(max_length=80)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    last_update = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'holidays'

        
  

class Patchcampaigns(models.Model):
    campaign_name = models.CharField(unique=True, max_length=50)
    campaign_startdate = models.DateField(blank=True, null=True)
    campaign_target_enddate = models.DateField(blank=True, null=True)
    patch_release_date = models.DateField(blank=True, null=True)
    srv_patch_list = models.TextField(blank=True, null=True)
    wks_patch_list = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'patchcampaigns'
        
class Querymanager(models.Model):
    title = models.CharField(max_length=80, blank=True, null=True)
    description = models.CharField(max_length=80, blank=True, null=True)
    lastupdated = models.DateTimeField(blank=True, null=True)
    lastuser = models.CharField(max_length=80, blank=True, null=True)
    allowedaccess = models.CharField(max_length=128, blank=True, null=True)
    querytext = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'querymanager'


class Rca(models.Model):
    rcaid = models.CharField(unique=True, max_length=80)
    content = models.TextField(blank=True, null=True)
    report = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=80, blank=True, null=True)
    lastupdated = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'rca'


class DiscrepancyServer(models.Model):
    devicename = models.CharField(unique=True, max_length=80)
    ipaddress = models.CharField(max_length=80)
    adindicator = models.CharField(max_length=80)
    ldindicator = models.CharField(max_length=80)
    kasindicator = models.CharField(max_length=80)
    deisindicator = models.CharField(max_length=80, blank=True, null=True)
    adcheck = models.IntegerField(blank=True, null=True)
    ldcheck = models.IntegerField(blank=True, null=True)
    kascheck = models.IntegerField(blank=True, null=True)
    deischeck = models.IntegerField(blank=True, null=True)
    comments = models.TextField()
    datehistory = models.TextField()
    commenthistory = models.TextField()
    lockby = models.CharField(max_length=80)
    last_update = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'srvdiscre'


class TrendTickets(models.Model):
    date = models.DateTimeField()
    groupe = models.CharField(max_length=200)
    count_in = models.IntegerField()
    count_out = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'trend_tickets'


class DiscrepancyWorkstation(models.Model):
    devicename = models.CharField(unique=True, max_length=80)
    ipaddress = models.CharField(max_length=80)
    adindicator = models.CharField(max_length=80)
    ldindicator = models.CharField(max_length=80)
    kasindicator = models.CharField(max_length=80)
    deisindicator = models.CharField(max_length=80, blank=True, null=True)
    adcheck = models.IntegerField(blank=True, null=True)
    ldcheck = models.IntegerField(blank=True, null=True)
    kascheck = models.IntegerField(blank=True, null=True)
    deischeck = models.IntegerField(blank=True, null=True)
    comments = models.TextField()
    datehistory = models.TextField()
    commenthistory = models.TextField()
    lockby = models.CharField(max_length=80)
    last_update = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'wksdiscre'    

class classicDashboardState(models.Model):
    username = models.CharField(max_length=80, blank=True, null=True)
    dashboard_state = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'classicdashboardstate'   
    
class ControlPlanManager(models.Model):
    control_id = models.CharField(primary_key=True, unique=True, max_length=80)
    category = models.CharField(max_length=80)
    domain = models.CharField(max_length=80)
    business_flag = models.CharField(max_length=80)
    zone = models.CharField(max_length=80)
    name = models.CharField(max_length=80)
    control_description = models.CharField(max_length=300)
    team_accountable = models.CharField(max_length=80)
    control_owner = models.CharField(max_length=80)
    
    control_processing_trigger_mode = models.CharField(max_length=80)
    control_processing_execution = models.CharField(max_length=80)
    control_processing_frequency = models.CharField(max_length=80)
    control_processing_repetition = models.CharField(max_length=80)
    control_processing_method = models.CharField(max_length=128)
    control_processing_responsible = models.CharField(max_length=80)
    
    control_data_type = models.CharField(max_length=80)
    control_data_description = models.CharField(max_length=128)
    control_data_target = models.CharField(max_length=80)
    control_data_sla = models.CharField(max_length=80)
    control_data_accountable = models.CharField(max_length=80)
    
    data_management_recording = models.CharField(max_length=80)
    data_management_storage = models.CharField(max_length=80)
    data_management_history = models.CharField(max_length=80)
    
    control_valuation_implementation = models.CharField(max_length=80)
    control_valuation_reliability = models.CharField(max_length=80)
    control_valuation_expectation = models.CharField(max_length=80)
    control_valuation_criticity = models.CharField(max_length=80)
    control_valuation_global_value = models.CharField(max_length=80)
    
    comments = models.TextField()
    
    last_updated = models.DateTimeField(auto_now=True)
    table_name = models.CharField(max_length=128)
    function_name = models.CharField(max_length=128)
    template_function = models.CharField(max_length=128)

    class Meta:
        managed = True
        db_table = 'controlplanmanager'
        indexes = [
            models.Index(fields=['control_processing_responsible'], name='responsible_idx'),
            models.Index(fields=['control_description'], name='description_idx'),
            models.Index(fields=['team_accountable'], name='accountable_idx'),
            models.Index(fields=['control_owner'], name='owner_idx'),
            models.Index(fields=['name'], name='name_idx'),
        ]
        
class customDashboard(models.Model):
    widget = models.CharField(max_length=80, primary_key=True)
    username = models.CharField(max_length=80)
    dashboard = models.CharField(max_length=80)
    title = models.CharField(max_length=80)
    selected_team = models.CharField(max_length=500)
    chart_size = models.TextField()
    widget_pos = models.TextField()

    class Meta:
        managed = True
        db_table = 'customdashboard'

hygie_portal/forms.py
# -*- coding: utf-8 -*-
"""Public forms."""
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import TextInput,EmailInput,PasswordInput

CustomUser = get_user_model()

class LoginForm(forms.Form):
    """Login form."""

    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField( widget=forms.PasswordInput())

    '''def __init__(self, *args, **kwargs):
        """Create instance."""
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = Users.objects.filter(username=self.username.data).first()
        if not self.user:
            self.username.errors.append('Unknown username')
            return False

        if not self.user.check_password(self.password.data):
            self.password.errors.append('Invalid password')
            return False

        if not self.user.active:
            self.username.errors.append('User not activated')
            return False
        return True'''
     
        
class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')   

hygie_portal/templates/users/control_plan_domain.html
{% extends "layout.html" %}

{% block head_js %}
{% endblock %}

{% block css %}

<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
{% load assets %}
{% assets "css_control_plan" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
{% endassets %}
{% endblock %}

{% block content %}
<div id="page-content-wrapper">
    <div class="container-fluid xyz">
        <div class="row">
            <div id="current-time-header" class="col-lg-12">
				<p>Last updated: <span id="current-time"></span> <button type="button" class="btn btn-default refresh-page"><i class="fa fa-refresh fa-fw" aria-hidden="true"></i></button></p>
			</div>
			<div class="col-lg-12">
				<nav aria-label="breadcrumb">
                    <ol class="breadcrumb default-color"></ol>
                </nav>
			</div>
		</div>
		<div class="row">
            <div class="col-lg-12">
				<div id="control-plan-domain" class="control-plan-block"></div>
			</div>
			<div class="col-lg-12">
				<div id="control-plan-breakdown" class="control-plan-block">
					<div id="accordion" role="tablist"></div>
				</div>
			</div>
		</div>
	</div>
</div>

{% include 'templatefiles/control_plan.html' %}

{% include 'popup_control_plan.html' %}

{% endblock %}

{% block js %}

{% assets "js_control_plan" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
<script>
var isFirefox = typeof InstallTrigger !== 'undefined';

var domainList = {{data|safe}};
dataList = {{data|safe}};
		
$(document).ready(function() {
    initJSHandlers();
    addBreadcrumb("domain", "Control Plan (Domain)");
	populateDomainBreakdown(domainList);
	
	
});

function domainClick(selectedDomain){

	var domainName = $(selectedDomain).attr('domain-name');
    
    addBreadcrumb("", domainName);
    
    var controlListPath = "['" + domainName + "']['controlList']";
    
	populateBreakdown(domainList[domainName]['controlList'], controlListPath);
	
    $('#control-plan-domain').hide();
}

</script>

{% endblock %}

hygie_portal/templates/users/control_plan_management.html
{% extends "layout.html" %}

{% block css %}  
    {% load assets %}
    {% assets "css_content_management" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

<style>

@media (min-width: 1200px) {
  .seven-cols .col-md-1,
  .seven-cols .col-sm-1,
  .seven-cols .col-lg-1 {
    width: 14.285714285714285714285714285714%;
  }
  .five-cols .col-md-1,
  .five-cols .col-sm-1,
  .five-cols .col-lg-1 {
    width: 20%;
  }
}

.fa-o {
    padding-right: 3px;
}

.ace_editor {
    border: 1px solid lightgray;
    margin: auto;
    height: 200px;
    width: 100%;
}
.scrollmargin {
    height: 80px;
    text-align: center;
}

</style>
{% endblock %}

{% block content %}

<div id="page-content-wrapper">
    <div class="row" id="control-plan-management-header">
        <div class="col-lg-12">
            <h4 class="center-header">Control Plan Management</h4>
        </div>
        <div class="col-lg-12">
            <button type="button" class="btn btn-default add-control"><i class="fa fa-plus fa-fw" aria-hidden="true"></i> Add Control</button>
        </div>
    </div>
    <div class="row">
        <div id="control-plan-management" class="col-lg-12">
            <div id="mandatory-fields" class="row">
                <div class="col-lg-3">
                    <label>*Control ID</label>
                    <input type="text" id="control-id" name="control_id" class="form-control" value="" />
                </div>
                <div class="col-lg-3">
                    <label>*Category</label>
                    <input type="text" id="control-category" name="control_category" class="form-control" value="" />
                </div>
                <div class="col-lg-3">
                    <label>*Domain</label>
                    <input type="text" id="control-domain" name="control_domain" class="form-control" value="" />
                </div>
                <div class="col-lg-3">
                    <label>*Business Flag</label>
                    <textarea type="text" id="control-businessflag" name="control_businessflag" class="form-control" value="" ></textarea>
                </div>
                <div class="col-lg-12">
                    <label>Last User</label>
                    <input type="text" id="control-lastuser" name="content_lastuser" class="form-control" value="" readonly/>
                </div>
                <div class="col-lg-12">
                    <label>Last Modified</label>
                    <input type="text" id="control-lastupdated" name="content_lastupdated" class="form-control" value="" readonly/>
                </div>
                <div class="col-lg-12">
                	<p><i>* These fields are mandatory</i></p>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-12 tag-center">
                    <button type="submit" class="btn btn-default btn-primary" id="content-management-cancel" onclick="cancelForm()">Cancel</button>
                    <button type="submit" class="btn btn-default btn-primary" id="content-management-save" onclick="saveContentData()">Save</button>
                    <button type="submit" class="btn btn-default btn-primary" id="content-management-delete" onclick="deleteContent()">Delete</button>
                </div>
            </div>
        </div> 
    </div>
</div>

{% endblock %}

{% block js %}

{% assets "js_content_management" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
<script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=nihbwjp8zrxdtcvguzk29c2i8uk9mdtylpgvr0d5rogr9pv0"></script>

<script>

    
$(document).ready(function(){

    $("#control-management-add").on("click", function(){
        // clear the form
        $("#control-list .button-value").html("Choose Content");
        $("#control-title").val("");
        $("#control-module").multiselect('clearSelection');
        $("#control-description").val("");
        $("#control-lastuser").val("");
        $("#control-lastupdated").val("");
        $("#control-allowedaccess").multiselect('clearSelection');
		tinymce.activeEditor.setContent("")
        
        
        //show form div
        $("#content-management").show();
        
        //hide delete button
        $("#content-management-delete").hide();
    });
    
    // ajax call to retrieve the data for the selected patch and device-list
    $("#content-management-edit").on('click', function(){
        data = {
           'csrf_token': '{{ csrf_token }}',
           'csrftoken': '{{ csrf_token }}',
           'content_title': $("#content-list .button-value").html()
        }
        var csrftoken = "{{ csrf_token }}"
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });

        $.ajax({
            url: '{% url  'hygie_portal:content_edit' %}'+'?local_tz='+local_zone,
            data: JSON.stringify(data, null, '\t'),
            type: 'POST',
            'async': false,
            contentType:'application/json;charset=UTF-8',
            dataType: "json",
            success: function(data) {
                console.log(data);
                // populate data in table
                populateContentData(data['content_details']);
            },
            error: function(error) {
                console.log(error);
            }
        });
    });
    
});

function populateContentData(data){
    //populate fields
    $("#content-id").val(data['id']);
    $("#content-list .button-value").val(data['title']);
    $("#content-title").val(data['title']);
    $("#content-description").val(data['description']);
    $("#content-module").multiselect('select', data['module'].split('|'));
    $("#content-lastuser").val(data['lastuser']);
    $("#content-lastupdated").val(moment.tz(data['lastupdated'], "Europe/Paris").tz(moment.tz.guess()).format("YYYY-MM-DD HH:mm:ss"));
    $("#content-allowedaccess").multiselect('select', data['allowedaccess'].split('|'));
    tinymce.activeEditor.setContent(data['contenttext'])
    
    
    //show form div and delete option
    $("#content-management").show();
    $("#content-management-delete").show();
}

function saveContentData(){
	
    var answer = swal({
            title: "Save this Content?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, Save!",
            closeOnConfirm: false
    },
    function(){
    	
    	
    	var savedData = {
    	    "id" : $("#content-id").val(),
	    	"title" : $("#content-title").val(),
	        "description" : $("#content-description").val(),
            "module" : $("#content-module").val().join("|"),
	        "contenttext" : tinymce.activeEditor.getContent(),
	        "lastuser" : '{{user.username}}',
	        "allowedaccess" : $("#content-allowedaccess").val().join("|")
    	};
    	
       
        console.log(savedData);
        
        data = {
           'csrf_token': '{{ csrf_token }}',
           'csrftoken': '{{ csrf_token }}',
           'content_settings': savedData
        }
        var csrftoken = "{{ csrf_token }}"
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });

        $.ajax({
            url: '{% url 'hygie_portal:content_save' %}'+'?local_tz='+local_zone,
            data: JSON.stringify(data, null, '\t'),
            type: 'POST',
            'async': false,
            contentType:'application/json;charset=UTF-8',
            dataType: "json",
            success: function(data) {
                if(data['status'] == 'ERROR'){ swal("Error!", "There was an error in saving the content", "error"); }
                else{
                	swal(data['status'], "Content has been saved", "success");
                    // update content list dropdown
                    $("#content-management-filters ul.dropdown-menu").empty();
                    $.each(data['content_list'], function(i, content){
                        $("#content-management-filters ul.dropdown-menu").append('<li><a href="#">' + content + '</a></li>');
                    });
                    
                    $("#content-list .button-value").html(savedData["title"]);
                    $("#content-list .button-value").val(savedData["title"]);
                    $("#content-management-filters #content-management-edit").removeAttr("disabled");
                    $("#content-management-delete").show();
                }
            },
            error: function(error) {
            	swal("Error!", "There was an error in saving the content", "error");
                console.log(error);
            }
        });
    });

}

function deleteContent(){
    var answer = swal({
            title: "Delete this content?",
            text: "Please note that the deletion is permanent and cannot be reverted.",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, Delete!",
            closeOnConfirm: false
    },
    function(){
    
        var data = {
           'csrf_token': '{{ csrf_token }}',
           'csrftoken': '{{ csrf_token }}',
           'content_title': $("#content-title").val()
        }
        
        var csrftoken = "{{ csrf_token }}"
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });

        $.ajax({
            url: '{% url 'hygie_portal:content_delete' %}'+'?local_tz='+local_zone,
            data: JSON.stringify(data, null, '\t'),
            type: 'POST',
            'async': false,
            contentType:'application/json;charset=UTF-8',
            dataType: "json",
            success: function(data) {
                console.log(data);
                swal("Deleted!", "The content has been deleted.", "success");
                // update campaign list dropdown
                $("#content-management-filters ul.dropdown-menu").empty();
                $.each(data['content_list'], function(i, content){
                    $("#content-management-filters ul.dropdown-menu").append('<li><a href="#">' + content + '</a></li>');
                });
                
                $("#content-list .button-value").html("Choose Content");
                $("#content-management-filters #content-management-edit").attr("disabled","disabled");
                $("#content-management").hide();
            },
            error: function(error) {
                swal("Error", "There was an error. Please contact the TSC Dev Team.", "error");
                console.log(error);
            }
        });
    });
    
}


function cancelForm(){
    //clear form
    $("#content-list .button-value").html("Choose Content");
    $("#content-title").val("");
    $("#content-description").val("");
    $("#content-module").multiselect('clearSelection');
    $("#content-lastuser").val("");
    $("#content-lastupdated").val("");
    $("#content-allowedaccess").multiselect('clearSelection');
    tinymce.activeEditor.setContent("")
    
    //hide form div
    $("#content-management").hide();
    $("#content-management-filters #content-management-edit").attr("disabled","disabled");
}

</script>
{% endblock %}