hygie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hygie_portal.urls')),
    path('admin/', admin.site.urls),
]

hygie_portal/urls.py
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from hygie_portal.forms import LoginForm
from . import views

app_name = "hygie_portal"

urlpatterns = [
    #path(r'login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name='login'),
    #path("", LoginView.as_view(template_name='public/login.html'), name='login'),
    path('login/', views.login_request, name='login'),
    path('', RedirectView.as_view(url='/login/')),
    
    path('profile/', views.profile, name='profile'),
    
    #path('home/', TemplateView.as_view(template_name='users/home_public.html'), name='home_public'),
    
    path('ticket_search/', views.ticket_search, name='ticket_search'),
    
    path('home/', views.home, name='home'),
    path('logout/', views.logout_request, name='logout'),
    
    path('change_view/<str:view_type>/', views.change_view , name='change_view'),
    
    path('members/', views.members, name='members'),
    path('holidays/', views.holidays, name='holidays'),
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('get_team_trends/', views.get_team_trends, name='get_team_trends'),
    path('classic_dashboard_load_group/', views.classic_dashboard_load_group, name='classic_dashboard_load_group'),
    path('classic_dashboard_state_save/', views.classic_dashboard_state_save, name='classic_dashboard_state_save'),
    
    path('custom_dashboard/', views.custom_dashboard, name='custom_dashboard'),
    path('save_settings/', views.save_settings, name='save_settings'),
    
    path('tickets/open/team/<str:team>/', views.team , name='team'),
    path('tickets_notes_json/', views.tickets_notes_json, name='tickets_notes_json'),
    
    
    path('security/<str:security_type>/', views.security , name='security'),
    path('security_details/<str:security_type>/', views.security_details , name='security_details'),
    #path('security_search/<str:security_type>/', views.security_search , name='security_search'),
    
    
    path('patch_followup', views.patch_followup, name='patch_followup'),
    path('patch_management', views.patch_management, name='patch_management'),
    path('patch_save', views.patch_save, name='patch_save'),
    path('patch_delete', views.patch_delete, name='patch_delete'),
    #path('patch_search/<str:security_type>/', views.patch_search , name='patch_search'),
    #path('patch_edit/<str:security_type>/', views.patch_edit , name='patch_edit'),
    #path('patch_customsearch/<str:security_type>/', views.patch_customsearch , name='patch_customsearch'),
    path('patch_detail_search/<str:security_type>/', views.patch_detail_search , name='patch_detail_search'),
    path('patch_device_info/<str:security_type>/', views.patch_device_info , name='patch_device_info'),
    path('tickets_notes_json', views.tickets_notes_json, name='tickets_notes_json'),
    
    path('discrepancy/<str:discrepancy_type>/', views.discrepancy , name='discrepancy'),
    path('except_discrepancy/<str:discrepancy_type>/', views.except_discrepancy , name='except_discrepancy'),
    path('discrepancy/ticketstatus', views.ticket_status, name='ticket_status'),
    
    path('ostype/<str:server_type>/', views.ostype , name='ostype'),
    
    path('cmdb/', views.cmdb, name='cmdb'),
    path('cmdb_json/', views.cmdb_json, name='cmdb_json'),    
    path('oneretail_json/', views.oneretail_json, name='oneretail_json'),  
    path('exclusion_json/', views.exclusion_json, name='exclusion_json'),
    path('oneretail_exclusion_json/', views.oneretail_exclusion_json, name='oneretail_exclusion_json'),
    path('oneretail_delete_json/', views.oneretail_delete_json, name='oneretail_delete_json'),
    path('delete_json/', views.delete_json, name='delete_json'),
    path('device_information/', views.device_information, name='device_information'),
    path('oneretail_device_information/', views.oneretail_device_information, name='oneretail_device_information'),
    
    path('quality/', views.quality, name='quality'),
    path('save_rca/', views.save_rca, name='save_rca'),
    path('edit_rcareport_quality/', views.edit_rcareport_quality, name='edit_rcareport_quality'),
    path('delete_rca/', views.delete_rca, name='delete_rca'),
    
    path('reporting_esurvey/', views.reporting_esurvey, name='reporting_esurvey'),
    path('get_esurvey_details/', views.get_esurvey_details, name='get_esurvey_details'),
    
    path('closed_tickets/', views.closed_tickets, name='closed_tickets'),
    path('reporting/topten/', views.reporting_topten, name='reporting_topten'),
    path('save_topten/', views.save_topten, name='save_topten'),
    
    path('reporting/tsc_calendar/', views.reporting_tsccalendar, name='reporting_tsccalendar'),
    path('reporting/nest_calendar/', views.reporting_nestcalendar, name='reporting_nestcalendar'),
    
    path('reporting/ticket_stats/', views.reporting_ticket_stats, name='reporting_ticket_stats'),
    path('reporting/<str:ticket_analysis_type>/', views.reporting_ticket_analysis , name='reporting_ticket_analysis'),
    
    path('reporting/integration_view/<str:view_mode>/', views.reporting_integration_view , name='reporting_integration_view'),

    path('hypervision_oneretail/', views.hypervision_oneretail, name='hypervision_oneretail'),
    
    path('control_plan_global/', views.control_plan_global, name='control_plan_global'),
    path('control_plan_ko/', views.control_plan_ko, name='control_plan_ko'),
    path('control_plan_domain/', views.control_plan_domain, name='control_plan_domain'),
    path('control_plan_businessflag/', views.control_plan_businessflag, name='control_plan_businessflag'),
    
    path('admintools/control_plan_management/', views.control_plan_management, name='control_plan_management'),
    
    path('admintools/query_management/', views.query_management, name='query_management'),
    path('admintools/query_edit/', views.query_edit, name='query_edit'),
    path('admintools/query_save/', views.query_save, name='query_save'),
    path('admintools/query_delete/', views.query_delete, name='query_delete'),
    
    
    path('admintools/content_management/', views.content_management, name='content_management'),
    path('admintools/content_save/', views.content_save, name='content_save'),
    path('admintools/content_edit/', views.content_edit, name='content_edit'),
    path('admintools/content_delete/', views.content_delete, name='content_delete'),
]

hygie_portal/models.py
from django.db import models

# Create your models here.
from django.db import models
from django import forms
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
import bcrypt
from datetime import datetime
#import ldap

class Applications(models.Model):
    name = models.CharField(unique=True, max_length=200)

    class Meta:
        managed = True
        db_table = 'applications'
        
class Contentmanager(models.Model):
    title = models.CharField(max_length=80, blank=True, null=True)
    description = models.CharField(max_length=80, blank=True, null=True)
    module = models.CharField(max_length=80, blank=True, null=True)
    contenttext = models.TextField(blank=True, null=True)
    lastupdated = models.DateTimeField(blank=True, null=True)
    lastuser = models.CharField(max_length=80, blank=True, null=True)
    allowedaccess = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'contentmanager'        
        
class CustomUser(AbstractUser):
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    #is_active = models.IntegerField(blank=True, null=True)
    is_admin = models.IntegerField(blank=True, null=True)
    role = models.CharField(max_length=256, blank=True, null=True)
    
    #USERNAME_FIELD = 'user'
    #REQUIRED_FIELDS = []
    
    '''def is_active(self):
        return True'''
        
    def set_is_admin(self, is_admin):
        self.is_admin = is_admin

    def set_role(self, role):
        self.last_update = datetime.now()
        self.role = role
        
class Holidays(models.Model):
    uid = models.CharField(unique=True, max_length=80)
    summary = models.CharField(max_length=80)
    region = models.CharField(max_length=80)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    last_update = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'holidays'

        
  

class Patchcampaigns(models.Model):
    campaign_name = models.CharField(unique=True, max_length=50)
    campaign_startdate = models.DateField(blank=True, null=True)
    campaign_target_enddate = models.DateField(blank=True, null=True)
    patch_release_date = models.DateField(blank=True, null=True)
    srv_patch_list = models.TextField(blank=True, null=True)
    wks_patch_list = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'patchcampaigns'
        
class Querymanager(models.Model):
    title = models.CharField(max_length=80, blank=True, null=True)
    description = models.CharField(max_length=80, blank=True, null=True)
    lastupdated = models.DateTimeField(blank=True, null=True)
    lastuser = models.CharField(max_length=80, blank=True, null=True)
    allowedaccess = models.CharField(max_length=128, blank=True, null=True)
    querytext = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'querymanager'


class Rca(models.Model):
    rcaid = models.CharField(unique=True, max_length=80)
    content = models.TextField(blank=True, null=True)
    report = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=80, blank=True, null=True)
    lastupdated = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'rca'


class DiscrepancyServer(models.Model):
    devicename = models.CharField(unique=True, max_length=80)
    ipaddress = models.CharField(max_length=80)
    adindicator = models.CharField(max_length=80)
    ldindicator = models.CharField(max_length=80)
    kasindicator = models.CharField(max_length=80)
    deisindicator = models.CharField(max_length=80, blank=True, null=True)
    adcheck = models.IntegerField(blank=True, null=True)
    ldcheck = models.IntegerField(blank=True, null=True)
    kascheck = models.IntegerField(blank=True, null=True)
    deischeck = models.IntegerField(blank=True, null=True)
    comments = models.TextField()
    datehistory = models.TextField()
    commenthistory = models.TextField()
    lockby = models.CharField(max_length=80)
    last_update = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'srvdiscre'


class TrendTickets(models.Model):
    date = models.DateTimeField()
    groupe = models.CharField(max_length=200)
    count_in = models.IntegerField()
    count_out = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'trend_tickets'


class DiscrepancyWorkstation(models.Model):
    devicename = models.CharField(unique=True, max_length=80)
    ipaddress = models.CharField(max_length=80)
    adindicator = models.CharField(max_length=80)
    ldindicator = models.CharField(max_length=80)
    kasindicator = models.CharField(max_length=80)
    deisindicator = models.CharField(max_length=80, blank=True, null=True)
    adcheck = models.IntegerField(blank=True, null=True)
    ldcheck = models.IntegerField(blank=True, null=True)
    kascheck = models.IntegerField(blank=True, null=True)
    deischeck = models.IntegerField(blank=True, null=True)
    comments = models.TextField()
    datehistory = models.TextField()
    commenthistory = models.TextField()
    lockby = models.CharField(max_length=80)
    last_update = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'wksdiscre'    

class classicDashboardState(models.Model):
    username = models.CharField(max_length=80, blank=True, null=True)
    dashboard_state = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'classicdashboardstate'   
    
class ControlPlanManager(models.Model):
    control_id = models.CharField(primary_key=True, unique=True, max_length=80)
    category = models.CharField(max_length=80)
    domain = models.CharField(max_length=80)
    business_flag = models.CharField(max_length=80)
    zone = models.CharField(max_length=80)
    name = models.CharField(max_length=80)
    control_description = models.CharField(max_length=300)
    team_accountable = models.CharField(max_length=80)
    control_owner = models.CharField(max_length=80)
    
    control_processing_trigger_mode = models.CharField(max_length=80)
    control_processing_execution = models.CharField(max_length=80)
    control_processing_frequency = models.CharField(max_length=80)
    control_processing_repetition = models.CharField(max_length=80)
    control_processing_method = models.CharField(max_length=128)
    control_processing_responsible = models.CharField(max_length=80)
    
    control_data_type = models.CharField(max_length=80)
    control_data_description = models.CharField(max_length=128)
    control_data_target = models.CharField(max_length=80)
    control_data_sla = models.CharField(max_length=80)
    control_data_accountable = models.CharField(max_length=80)
    
    data_management_recording = models.CharField(max_length=80)
    data_management_storage = models.CharField(max_length=80)
    data_management_history = models.CharField(max_length=80)
    
    control_valuation_implementation = models.CharField(max_length=80)
    control_valuation_reliability = models.CharField(max_length=80)
    control_valuation_expectation = models.CharField(max_length=80)
    control_valuation_criticity = models.CharField(max_length=80)
    control_valuation_global_value = models.CharField(max_length=80)
    
    comments = models.TextField()
    
    last_updated = models.DateTimeField(auto_now=True)
    table_name = models.CharField(max_length=128)
    function_name = models.CharField(max_length=128)
    template_function = models.CharField(max_length=128)

    class Meta:
        managed = True
        db_table = 'controlplanmanager'
        indexes = [
            models.Index(fields=['control_processing_responsible'], name='responsible_idx'),
            models.Index(fields=['control_description'], name='description_idx'),
            models.Index(fields=['team_accountable'], name='accountable_idx'),
            models.Index(fields=['control_owner'], name='owner_idx'),
            models.Index(fields=['name'], name='name_idx'),
        ]
        
class customDashboard(models.Model):
    widget = models.CharField(max_length=80, primary_key=True)
    username = models.CharField(max_length=80)
    dashboard = models.CharField(max_length=80)
    title = models.CharField(max_length=80)
    selected_team = models.CharField(max_length=500)
    chart_size = models.TextField()
    widget_pos = models.TextField()

    class Meta:
        managed = True
        db_table = 'customdashboard'

hygie_portal/forms.py
# -*- coding: utf-8 -*-
"""Public forms."""
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import TextInput,EmailInput,PasswordInput

CustomUser = get_user_model()

class LoginForm(forms.Form):
    """Login form."""

    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField( widget=forms.PasswordInput())

    '''def __init__(self, *args, **kwargs):
        """Create instance."""
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = Users.objects.filter(username=self.username.data).first()
        if not self.user:
            self.username.errors.append('Unknown username')
            return False

        if not self.user.check_password(self.password.data):
            self.password.errors.append('Invalid password')
            return False

        if not self.user.active:
            self.username.errors.append('User not activated')
            return False
        return True'''
     
        
class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')   

hygie_portal/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home', next=request.endpoint, params=request.view_args)}}">log in</a>
        </p>
    </div>
</div>
{% endblock %}

hygie_portal/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{% block meta_description %}{% endblock %}">
	<meta name="author" content="{% block meta_author %}{% endblock %}">
    <title>{% block page_title %} {{my_config.PAGE_TITLE}} {% endblock %}</title>
	{% load static %}
	<link rel="shortcut icon" href="{% static 'h-icon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Plaster|Monoton" rel="stylesheet">
    <link href="/static/libs/bootstrap-toggle-master/css/bootstrap-toggle.css" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
     
    <style>
        .panel-yellow > .panel-heading {
            border-color: {{config.COLOR_SCHEME.MEDIUM}} !important;
            background-color: {{config.COLOR_SCHEME.MEDIUM}} !important;
            color: #000000 !important;
         }
         .panel-green > .panel-heading {
            border-color: {{config.COLOR_SCHEME.LOW}} !important;
            background-color: {{config.COLOR_SCHEME.LOW}} !important;
            color: #000000 !important;
        }
        .panel-info > .panel-heading {
            border-color: {{config.COLOR_SCHEME.PLANNED}} !important;
            background-color: {{config.COLOR_SCHEME.PLANNED}} !important;
        }


    </style>
	<link rel="stylesheet" href="/static/css/cmdb_style.css">
    <link rel="stylesheet" type="text/css" href="/static/css/sweetalert.css">
    <script src="/static/js/sweetalert.min.js"></script>

    {% block css %}
	{% load assets %}
    {% assets "css_all" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
    {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="{% block body_class %}{% endblock %}" >
	{% block body %} 
    
    {% include "nav_top.html" %}
    <div class="wrapper">
        {% include "nav_left.html" %}
        
        <div id="content">
            <button type="button" id="leftsidebarCollapse" class="btn navbar-btn">
                <i class="glyphicon glyphicon-chevron-right"></i>
            </button>
       
        {% block content %}	
            
        {% endblock %}
            <a id="back-to-top" href="#" class="btn btn-primary btn-md back-to-top" role="button" title="Back to Top" data-toggle="tooltip" data-placement="top">
                <span class="glyphicon glyphicon-chevron-up"></span>
            </a>
        </div>
        <div class="overlay"></div>
    </div>
    
    <!--</div>-->
    <!-- /#wrapper -->
    <!-- Custom Theme JavaScript -->
	<!-- JavaScript at the bottom for fast page loading -->

    {% block js %}
	{% load assets %}
    {% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    {% endblock %}
        
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
        
    <script type="text/javascript">
    $(document).ready(function(){
    
        //generateNavSideBar();
        
        /** START NEW SIDE BAR **/
        $("#leftsidebar").mCustomScrollbar({
            theme: "minimal"
        });

        // when opening the sidebar
        $('#leftsidebarCollapse').on('click', function () {
            // open sidebar
            $('#leftsidebar').addClass('active');
            // fade in the overlay
            $('.overlay').fadeIn();
            $('#leftsidebar .collapse.in').toggleClass('in');
            $('#leftsidebar a[aria-expanded=true]').attr('aria-expanded', 'false');
        });

       
        // if dismiss or overlay was clicked
        $('#dismiss, .overlay').on('click', function () {
          // hide the sidebar
          $('#leftsidebar').removeClass('active');
          // fade out the overlay
          $('.overlay').fadeOut();
          //clear ticket search form
          $("#ticket_search")[0].reset();
        });
        /** END NEW SIDE BAR **/
        
        /* back to top button */
        $(window).scroll(function () {
            if ($(this).scrollTop() > 50) {
                $('#back-to-top').fadeIn();
            } else {
                $('#back-to-top').fadeOut();
            }
        });
        // scroll body to 0px on click
        $('#back-to-top').click(function () {
            $('#back-to-top').tooltip('hide');
            $('body,html').animate({
                scrollTop: 0
            }, 800);
            return false;
        });
        
        //$('#back-to-top').tooltip('show');
        /* end back to top button */
                
    });
        

    //get local time zone
    function get_time_zone_offset() {
        var current_date = new Date();
        return parseInt(-current_date.getTimezoneOffset() / 60);
    }

    local_zone = moment.tz.guess();
    
    $("a.side_click").each(function(index){
        var _href = $(this).attr("href");
        $(this).attr("href", _href + '?local_tz='+local_zone);
    });


    $('#ticket_search').on('submit', function() {
        var formAction = $('#ticket_search').attr('action');
        if (formAction.indexOf("local_tz") <= 0){
            $('#ticket_search').attr('action', formAction + "?local_tz="+local_zone);
        }
    });


    $(".nav li.disabled a").click(function() {
        return false;
    });
    
    
    </script>
    <script src="/static/libs/bootstrap-toggle-master/js/bootstrap-toggle.js"></script>
	<!-- end scripts -->
	{% endblock %}
</body>

</html>

hygie_portal/templates/nav_top.html
<!-- Navigation -->
{% load static %}
<nav class="navbar navbar-default no-margin">

<!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header fixed-brand">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topnavbar" id="menu-toggle">
          <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
        </button>
        <!-- <a class="navbar-brand" href="{{ public.home }}" onclick="location.href=this.href+'?local_tz='+local_zone;return false;"><img src="{% static 'img/logo.png' %}"> Hygie </a> -->
        <a class="navbar-brand" href="{% url 'hygie_portal:home' %}" onclick="location.href=this.href+'?local_tz='+local_zone;return false;"> HYGIE </a>
    </div><!-- navbar-header-->

    <div class="collapse navbar-collapse" id="topnavbar">
        <!-- <ul class="nav navbar-nav">
            <li class="active" ><button class="navbar-toggle collapse in" data-toggle="collapse" id="menu-toggle-2"> <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> </button></li>
        </ul> -->
        <ul class="nav navbar-nav navbar-right">
            {% load decode %}
            <li><a href="{% url 'hygie_portal:profile' %}">Welcome {{ user.first_name|decode }}!</a></li>
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><i class="fa fa-eye fa-fw"></i>View<span class="caret"></span></a>
                <ul class="dropdown-menu">
                <li {% if request.session.view == "sla" %}class="disabled"{% endif %}><a href="{% url 'hygie_portal:change_view' view_type='sla' %}"><i class="fa fa-bar-chart-o fa-fw"></i>SLA</a></li>
                <li {% if request.session.view == "priority" %}class="disabled"{% endif %}><a href="{% url 'hygie_portal:change_view' view_type='priority' %}"><i class="fa fa-trophy fa-fw"></i>Priority</a></li>
                </ul>
           </li>
           {% if user.is_admin %}
           <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><i class="fa fa-gear fa-fw"></i>Admin Tools<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'hygie_portal:members' %}"><i class="fa fa-users fa-fw"></i>Members</a></li>
                  <li><a href="{% url 'hygie_portal:holidays' %}"><i class="fa fa-calendar fa-fw"></i>Holidays</a></li>
                </ul>

           </li>
           {% endif %}
           <li><a href="{% url 'hygie_portal:logout' %}"><i class="fa fa-sign-out fa-fw"></i>Logout</a></li> 
        </ul>
    </div><!-- bs-example-navbar-collapse-1 -->
</nav>

hygie_portal/templates/popup_control_plan.html
<!-- Modal Popup for Control Plan -->
<div id="control-plan-modal" class="modal fade" role="dialog">
    <div class="modal-dialog note-modal">
    <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title text-center"><span id="modal-control-name"></span></h3>
            </div>
            <div class="modal-body">
				
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

hygie_portal/templates/popup_description.html
<!-- Modal Popup for Description -->
<div id="ticket_description" class="modal fade" role="dialog">
    <div class="modal-dialog description-modal">
    <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Ticket Description - <span id="modal-ticket-no"></span></h4>
            </div>
            <div class="modal-body modal-body-desc">
                <p id="modal-description"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

hygie_portal/templates/popup_kaspersky.html
<!-- Modal Popup for Notes -->
<div id="security_details" class="modal fade" role="dialog">
    <div class="modal-dialog detail-modal">
    <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Not Updated > 7 days {{security_type}} - <span id="modal-ticket-no"></span></h4>
            </div>
            <div class="modal-body modal-body-note">
                <div id="visualization_wrap"> 
                <div id="notes_time_line"></div>
                </div>
                <table width="100%" class="table table-bordered table-hover table-striped table-inverse" id="details-table">
                     <thead>
                     <tr>
                         <th>HostName</th>
                         <th>Version</th>
                         <th>Virus Defintion Date</th>
                         <th>Group Name</th>
                     </tr>
                     </thead>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

hygie_portal/templates/popup_resolution.html
<!-- Modal Popup for Resolution -->
<div id="ticket_resolution" class="modal fade" role="dialog">
    <div class="modal-dialog resolution-modal">
    <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Ticket Resolution - <span id="modal-ticket-no"></span></h4>
            </div>
            <div class="modal-body modal-body-desc">
                <p id="modal-resolution"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>